"""add status to projects

Revision ID: 786f58ce4406
Revises: 07dceec1beaf
Create Date: 2026-08-11 03:32:02.226889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786f58ce4406'
down_revision: Union[str, None] = '07dceec1beaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.String(), server_default='enquiry', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
