"""add tenants table

Sprint 008 (docs/DECISIONS.md ADR-025) — first of two revisions. Creates
the tenants table only; the second revision (down_revision points here)
converts the 7 existing tenant_id columns into real FKs against it. Split
from one bigger autogenerated diff into two for a clean, independently
reviewable/revertible step each.

Revision ID: f7041a28f140
Revises: 786f58ce4406
Create Date: 2026-08-13 00:30:02.852860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7041a28f140'
down_revision: Union[str, None] = '786f58ce4406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )


def downgrade() -> None:
    op.drop_table('tenants')
